name: Trigger-Test
on: [push]
jobs:
  build-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Tosca Authetication
        id: Tosca_Authetication
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://wael.oktapreview.com/oauth2/default/v1/token?client_id=${{secrets.TOSCA_AUTH_CLIENT_ID}}&client_secret=${{secrets.TOSCA_AUTH_CLIENT_SECRET}}&scope=E2GApi&grant_type=client_credentials"
          method: 'POST'
          customHeaders: '{"Content-Type":"application/x-www-form-urlencoded"}'
          # data: '{"client_secret":"${{secrets.TOSCA_AUTH_CLIENT_SECRET}}","client_id":"${{secrets.TOSCA_AUTH_CLIENT_ID}}","scope","E2GApi","grant_type":"client_credentials"}'
      - name: Show Response
        run: |
          echo ${{ steps.Tosca_Authetication.outputs.response }}
          echo ${{ steps.Tosca_Authetication.outputs.response.access_token }}
          echo ${{ fromJson(steps.Tosca_Authetication.outputs.response).access_token }}
          echo "Tosca Authetication"
        env:
          TOSCA_AUTH_Bearer: ${{ fromJson(steps.Tosca_Authetication.outputs.response).access_token }}
      - name: Tosca ExecuteFlow
        id: Tosca_ExecuteFlow
        run: |
          echo "Tosca ExecuteFlow"
          echo $TOSCA_AUTH_Bearer
          echo "begin curl"
          curl --location --request GET 'https://wael.my.tricentis.com/_e2g/api/agents' \
          --header 'Authorization: Bearer eyJraWQiOiIteE91bjMteTlmX25Ka19qajZWaHZxcTdSdGdIc0xCNzRTZ3JROFhfNktVIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULk9USGF0cGc5T24yVUtuNER5UmVxRUY4LTdWZXhOYUlJbXg3TDNOenNLMmMiLCJpc3MiOiJodHRwczovL3dhZWwub2t0YXByZXZpZXcuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTY1NTczODE0OCwiZXhwIjoxNjU1NzQxNzQ4LCJjaWQiOiJTd2FnZ2VyIiwidWlkIjoiMDB1NDYycTJ6aTlYMTlyMHkweDciLCJzY3AiOlsiRTJHQXBpIiwicHJvZmlsZSIsIm9wZW5pZCIsImVtYWlsIl0sImF1dGhfdGltZSI6MTY1NTczODEyOSwic3ViIjoid2FlbC5hbWVyQGdtYWlsLmNvbSIsIm5hbWUiOiJXYWVsIEFtZXIiLCJncm91cHMiOlsiRXZlcnlvbmUiLCJUcmljZW50aXMgQ2xvdWQgdXNlcnMiXSwiZW1haWwiOiJ3YWVsLmFtZXJAZ21haWwuY29tIn0.cK32CWZ4O9oJ33JEOPjOVjC9ramBDE1bO9B-Eq71yfoiaydyGkqhD_MXOLhdmcIhm_ujG-M2_Daj4QwiizOHBGuVsrCxzIldZuzpoh--22dDBBafdRIsP9x7ZM9H7pWFB1Mw4pb6NboT8gkXtBrcJfOxmKxiaq2VLmViGEiA-eUJneFeYQyTzzodxn2HzWpBePEXHkk-lMDb3Ya2Th1_nP2ae6k0LPVQsALWMYZDzk9tYYp8VB2RtmGsaStC3G9KiJzcxxyNPnJ4UkddqNk-wMLY8UOzgf9TYuqNaOmXLk3SdPCPgPz9eazkp6GWRHSsBUUfjIL8mskVr3rcU4WXtw' \
          --header 'Content-Type: application/json' \
          --header 'X-Tricentis: OK' \
          --header 'Accept-Language: de'
      - name: Tosca GetFlowStatus
        id: Tosca_GetFlowStatus
        run: |
          echo "Tosca GetFlowStatus"
      - name: Deploy TODO Frontend Test
        id: Deploy_Frontend_TEST
        run: |
          echo "Deploy TODO Frontend Test"
