name: TODO-APP-CI
on: [push]
jobs:
  TODO-APP-CI:
    runs-on: "ubuntu-latest"
    steps:
      - name: Tosca Authetication
        id: Tosca_Authetication
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://wael.oktapreview.com/oauth2/default/v1/token?client_id=${{secrets.TOSCA_AUTH_CLIENT_ID}}&client_secret=${{secrets.TOSCA_AUTH_CLIENT_SECRET}}&scope=E2GApi&grant_type=client_credentials"
          method: 'POST'
          customHeaders: '{"Content-Type":"application/x-www-form-urlencoded"}'          
      - name: Show Response
        run: |
          echo ${{ steps.Tosca_Authetication.outputs.response }}
          echo ${{ fromJson(steps.Tosca_Authetication.outputs.response)}}
          echo ${{ fromJson(steps.Tosca_Authetication.outputs.response).access_token }}

      - name: Tosca TEST AGENT
        id: Tosca_AGENT
        uses: fjogeleit/http-request-action@v1
        env:
          TOSCA_AUTH_Bearer: ${{ fromJson(steps.Tosca_Authetication.outputs.response).access_token }}
        with:
          url: "https://wael.my.tricentis.com/default/_e2g/api/flowExecutions"
          method: 'POST'
          customHeaders: '{"Content-Type":"application/json","X-Tricentis":"OK"}'
          bearerToken: ${{ fromJson(steps.Tosca_Authetication.outputs.response).access_token }}
          data: '{"flowId":"${{secrets.TOSCA_AUTH_FLOWID}}","timeoutInMinutes":"3000"}'
      - name: Show Response
        run: |
          echo "Tosca ExecuteFlow"
          echo ${{ steps.Tosca_AGENT.outputs.response }}
          echo ${{ fromJson(steps.Tosca_AGENT.outputs.response) }}
          echo ${{ fromJson(steps.Tosca_AGENT.outputs.response).id }}


      - name: Tosca ExecuteFlow
        id: Tosca_ExecuteFlow
        uses: fjogeleit/http-request-action@v1
        env:
          TOSCA_AUTH_Bearer: ${{ fromJson(steps.Tosca_Authetication.outputs.response).access_token }}
        with:
          url: "https://wael.my.tricentis.com/default/_e2g/api/flowExecutions"
          method: 'POST'
          customHeaders: '{"Content-Type":"application/json","X-Tricentis":"OK"}'
          bearerToken: ${{ fromJson(steps.Tosca_Authetication.outputs.response).access_token }}
          data: '{"flowId":"${{secrets.TOSCA_AUTH_FLOWID}}","timeoutInMinutes":"3000"}'
      - name: Show Response
        run: |
          echo "Tosca ExecuteFlow"
          echo ${{ steps.Tosca_ExecuteFlow.outputs.response }}
          echo ${{ fromJson(steps.Tosca_ExecuteFlow.outputs.response) }}
          echo ${{ fromJson(steps.Tosca_ExecuteFlow.outputs.response).id }}

      - name: Tosca GetFlowStatus
        id: Tosca_GetFlowStatus
        uses: fjogeleit/http-request-action@v1
        env:
          TOSCA_AUTH_EXECUTEDFLOW_ID: ${{ fromJson(steps.Tosca_ExecuteFlow.outputs.response).id }}
        with:
          url: "https://wael.my.tricentis.com/default/_e2g/api/executionPackageRuns/$TOSCA_AUTH_EXECUTEDFLOW_ID"
          method: 'GET'
          customHeaders: '{"Authorization":"Bearer ${{ fromJson(steps.Tosca_Authetication.outputs.response).access_token }}","Content-Type":"application/json","X-Tricentis":"OK"}'
      - name: Show Response
        run: |
          echo "Tosca GetFlowStatus"
          echo $TOSCA_AUTH_EXECUTEDFLOW_ID
          echo ${{ steps.Tosca_GetFlowStatus.outputs.response }}
          echo ${{ fromJson(steps.Tosca_GetFlowStatus.outputs.response) }}      
      - name: Deploy TODO Frontend Test
        id: Deploy_Frontend_TEST
        run: |
          echo "Deploy TODO Frontend Test"
