name: Trigger-Test
on: [push]
jobs:
  build-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Tosca Authetication
        id: Tosca_Authetication
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://fhbkhorvath.oktapreview.com/oauth2/default/v1/token?client_secret=Tricentis_Cloud_API&client_id=rp3qiVhaX5hSff_h_6icMKHeOYE4zGk5pGGf3q_4&scope=E2GApi&grant_type=client_credentials"
          method: 'POST'
          customHeaders: '{"Content-Type":"application/x-www-form-urlencoded"}'
          # data: '{"client_secret":"${{secrets.TOSCA_AUTH_CLIENT_SECRET}}","client_id":"${{secrets.TOSCA_AUTH_CLIENT_ID}}","scope","E2GApi","grant_type":"client_credentials"}'
      - name: Show Response
        run: |
          echo ${{ steps.Execute_Flow.outputs.response }}
          echo "Tosca Authetication"
          echo ${{secrets.TOSCA_AUTH_CLIENT_ID}}
          echo $TOSCA_AUTH_CLIENT_ID
        env:
          TOSCA_AUTH_Bearer: ${{ steps.Execute_Flow.outputs.response }}
      - name: Tosca ExecuteFlow
        id: Tosca_ExecuteFlow
        run: |
          echo "Tosca ExecuteFlow"
          echo $TOSCA_AUTH_Bearer
      - name: Tosca GetFlowStatus
        id: Tosca_GetFlowStatus
        run: |
          echo "Tosca GetFlowStatus"
      - name: Deploy TODO Frontend Test
        id: Deploy_Frontend_TEST
        run: |
          echo "Deploy TODO Frontend Test"
