name: Trigger-Test
on: [push]
jobs:
  build-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Tosca Authetication
        id: Tosca_Authetication
        run: |
          echo "Tosca Authetication"
          echo ${{secrets.TOSCA_AUTH_CLIENT_ID}}
          echo $TOSCA_AUTH_CLIENT_ID
        env:
          TOSCA_AUTH_CLIENT_ID: ${{secrets.TOSCA_AUTH_CLIENT_ID}}}
      - name: Tosca ExecuteFlow
        id: Tosca_ExecuteFlow
        run: |
          echo "Tosca ExecuteFlow"
      - name: Tosca GetFlowStatus
        id: Tosca_GetFlowStatus
        run: |
          echo "Tosca GetFlowStatus"
      - name: Deploy TODO Frontend Test
        id: Deploy_Frontend_TEST
        run: |
          echo "Deploy TODO Frontend Test"
